### ISSUE TITLE
Plugins should be configureable via config.yml

### ISSUE THREAD

**Issue by dadav** [evilsocket/pwnagotchi#129]
It would be nice if i could configure the plugins via `config.yml`, escpecially if i overwrite the code regulary.

Maybe something like:

```yaml
plugins:
  twitter:
    api: 'key'
  wpa-sec:
    api: 'key'
```

The activation is implicit. If configuration is there, i want to activate that plugin.
