### ISSUE TITLE
Auto-backup-plugin

### ISSUE THREAD

**Issue by dadav** [evilsocket/pwnagotchi#139]
I imagine the following:

```yaml
plugins:
  auto-backup:
    enabled: true
    files:
      - /root/brain.nn
      - /root/brain.json
      - ....
    backup_cmd: tar czf /tmp/backup.tar.gz {files}
    upload_cmd: scp /tmp/backup.tar.gz 10.0.0.1:/backups/pwnagotchi/backup$(date).tar.gz
```
