### ISSUE TITLE
use own subdir for every custom_plugin

### ISSUE THREAD

**Issue by xenDE** [evilsocket/pwnagotchi#247]
after testing my sound.py plugin as default-plugin with RC2, i found problems:

- my sound.py plugin uses a subdir "sound" with a helper bash script and wave files
- the /sound/ subdir is not copied/installed on "python3 setup.py sdist bdist_wheel && pip3 install --no-deps --force-reinstall /usr/local/src/pwnagotchi/dist/pwnagotchi*.whl"

so i think i want to install my sound plugin as custom_plugin, but with little changes for easy handling/clone plugins from a second git repo:

- the custom_plugin directory is already configurable:
```
    # custom plugins path, if null only default plugins with be loaded
    custom_plugins: /usr/local/pwnagotchi/plugins
    plugins:
      pwna-sound:
        enabled: true
        sound-dir: default
        text2speech-use: false
        text2speech-lang: en-US
...
```
- use a subdir for every plugin (dirname=pluginname) with own defaults config (so it can be cloned from git) 

- use a subdir for every plugin (dirname=pluginname) with own defaults config (so it can be cloned from git)
```
example:
/usr/local/pwnagotchi/plugins
  /pwna-sound
    /.git
    /pwna-sound.py
    /helperscript.sh
    /sounds
      /soundfile.wav
```
example plugin: https://github.com/xenDE/pwna-sound
