### ISSUE TITLE
Need help to get the Waveshare 2.9 inch e-Paper Display working

### ISSUE THREAD

**Issue by cynay** [evilsocket/pwnagotchi#360]
Hi 
I need help to get the very cool pwnagotchi working with the 2.9 Inch e-Paper Display working.
Everything is working except the Display. I can connect over the USB-Ethernet and it's working.
I'm happy for any input :)

Thanks cynay

**Comment by rooty0** [comment]
Do you have 
```yaml
ui:
  display:
    type: 'waveshare_2'
    color: 'black'
```

in your `/etc/pwnagotchi/config.yml` ?
