### ISSUE TITLE
GPIO Button Plugin

### ISSUE THREAD

**Issue by ratmandu** [evilsocket/pwnagotchi#449]
**Is your feature request related to a problem? Please describe.**
Adding support for a GPIO button plugin. 
This allows you to run an arbitrary command when a button is pressed.

This is configurable via config.yml with the following setup:
```yml
plugins:
    gpio_buttons:
        enabled: false
        #The following is a list of the GPIO number for your button, and the command you want to run when it is pressed
        gpios:
            - 20: 'sudo touch /root/.pwnagotchi-auto && sudo systemctl restart pwnagotchi'
            - 21: 'shutdown -h now'
```
