### ISSUE TITLE
[BUG] bt-tether not connecting to an Android phone

### ISSUE THREAD

**Issue by hackabean** [evilsocket/pwnagotchi#508]
Hello, thanks for an amazing project. I have been trying to set up bt-tethering option since yesterday. I have installed latest release and read on on the latest changes regarding bt-tether. For this I have used new config.yml that has been recently updated. My config.yml about bt-tether looks like this:
```
        bt-tether:
            enabled: true # if you want to use this, set ui.display.video.address to 0.0.0.0
            devices:
              android-phone:
                enabled: true
                search_order: 1 # search for this first
                mac: 'EC:D0:XX:XX:XX:XX' # mac of your bluetooth device
                ip: '192.168.44.44' # ip from which your pwnagotchi should be reachable
                netmask: 24
                interval: 1 # check every minute for device
                scantime: 10 # search for 10 seconds
                max_tries: 10 # after 10 tries of "not found"; don't try anymore
                share_internet: false
                priority: 1 # low routing priority; ios (prio: 999) would win here
              ios-phone:
                enabled: false
                search_order: 2 # search for this second
                mac: ~ # mac of your bluetooth device
                ip: '172.20.10.6' # ip from which your pwnagotchi should be reachable
                netmask: 24
                interval: 5 # check every 5 minutes for device
                scantime: 20
                max_tries: 0 # infinity
                share_internet: false
                priority: 999 # routing priority

```

I also replaced bt-tether.py with this updated one https://github.com/evilsocket/pwnagotchi/blob/master/pwnagotchi/plugins/default/bt-tether.py.

I have paired the phone and rpi0w manually using bluetoothctl, it said that the pairing was successful but it immediately disconnected shortly after. Same situation with an iphone as well.

What have I missed, is there anything else I can try ?
