### ISSUE TITLE
GPS not pulling data

### ISSUE THREAD

**Issue by elipsius** [evilsocket/pwnagotchi#541]
I have gpsd configured with USB based GPS receiver, test using cgps and data pulls and shows location data and time correctly.  When I enable it in my config the json files show up but location. Data is has lats and longs always 0.

Not sure what I'm missing or of this is a bug.

**Comment by elipsius** [comment]
My configuration:

```
#
main:
    name: 'manigotchi'                                                                                                                      plugins:
     gps:
            enabled: true
            speed: 19200
            device: /dev/ttyUSB0
```
