### ISSUE TITLE
Can't connect to web ui via usb

### ISSUE THREAD

**Issue by Lopuzal** [evilsocket/pwnagotchi#781]
I can access to bettercap at 10.0.0.2:80 or pwnagotchi.local:80 but I can't connect to 10.0.0.2:8082 or pwnagotchi.local:8082 which is supposed to be the web ui server (I also tried 8080 as port)

Here's my config.yml
```
main:
  name: 'pwnagotchi'
  plugins:
    grid:
      enabled: true
      report: true
   plugins:
     bt-tether:
       enabled: true
       devices:
         my-phone1:
           enabled: true
           mac: '7E:3C:46:00:00:C8'
           ip: '192.168.44.47'
           netmask: 24
           interval: 1
           share_internet: true
           priority: 99
           max_tries: 0
         my-phone1:
           enabled: true
           search_order: 1
           mac: '00:1A:7D:DA:71:0A'
           ip: '192.168.44.47'
           netmask: 24
           interval: 1
           scantime: 15
           share_internet: true
           priority: 9
           max_tries: 0 
ui:
    web:
      enabled: true
      address: '10.0.0.2'
      username: aaaa
      password: aaaa
      port: 8082

```
